In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam


X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

# Correct outputs for each gate
y_and = np.array([[0], [0], [0], [1]])
y_or  = np.array([[0], [1], [1], [1]])
y_xor = np.array([[0], [1], [1], [0]])

# Function to create and train a simple neural network
def create_and_train_nn(input_dim, output_dim, X, y, epochs=1000):
    model = Sequential()
    model.add(Dense(1, input_dim=input_dim, activation='sigmoid'))  # Cause for here AND and OR are linear seperable : For AND, OR (1 layer)
    model.compile(optimizer=Adam(learning_rate=0.5), loss='binary_crossentropy', metrics=['accuracy'])

    model.fit(X, y, epochs=epochs, verbose=0)
    return model

In [2]:
# AND gate
print("=== AND ===")
print("Inputs:\n", X)
print("Correct AND outputs:\n", y_and.flatten())
model_and = create_and_train_nn(2, 1, X, y_and, epochs=100)
pred_and = model_and.predict(X).round().astype(int)
print("Predicted AND:\n", pred_and.flatten(), "\n")

=== AND ===
Inputs:
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Correct AND outputs:
 [0 0 0 1]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
Predicted AND:
 [0 0 0 1] 



In [3]:
# OR gate
print("=== OR ===")
print("Inputs:\n", X)
print("Correct OR outputs:\n", y_or.flatten())
model_or = create_and_train_nn(2, 1, X, y_or, epochs=100)
pred_or = model_or.predict(X).round().astype(int)
print("Predicted OR:\n", pred_or.flatten(), "\n")

=== OR ===
Inputs:
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Correct OR outputs:
 [0 1 1 1]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
Predicted OR:
 [0 1 1 1] 



In [4]:
# XOR gate (requires a hidden layer for non-linearity) - (I am thinking of using another activation function in that hidden layer sha..)
print("=== XOR ===")
print("Inputs:\n", X)
print("Correct XOR outputs:\n", y_xor.flatten())
model_xor = Sequential()
model_xor.add(Dense(2, input_dim=2, activation='sigmoid'))  # Cause I am using XOR here so : Hidden layer with 2 units
model_xor.add(Dense(1, activation='sigmoid'))  # Output layer
model_xor.compile(optimizer=Adam(learning_rate=0.5), loss='binary_crossentropy', metrics=['accuracy'])

model_xor.fit(X, y_xor, epochs=100, verbose=0)
pred_xor = model_xor.predict(X).round().astype(int)
print("Predicted XOR:\n", pred_xor.flatten())

=== XOR ===
Inputs:
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Correct XOR outputs:
 [0 1 1 0]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
Predicted XOR:
 [0 1 0 0]
